import { GET_ALL_POSTS } from '@/graphql/queries';
import { ApolloClient, InMemoryCache } from '@apollo/client'
import Head from 'next/head'
import Link from 'next/link';
import Image from 'next/image'
import Hero from '@/components/assets/hero.jpg'


export default function Home({ posts }) {
  console.log(posts);
  return (

    <div>
      <Head>
        <title>Raff Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='main'>MyBlog by Raff</h1>
      <div className='hero_main'>
        <Image className='hero' src={Hero}></Image>
      </div>
      <p className='maindesc'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin eu metus turpis. Cras posuere blandit erat, eu maximus erat rutrum ac. Aenean suscipit et ligula nec feugiat. Sed maximus purus nunc, ut sagittis neque placerat ac. </p>
      <br />
      <h2 className='allpost'>All Posts</h2>
      <br />

<div className='card_out'>
      {posts.map((val, i) => {
        return (
          <Link key={i} href={val.attributes.urlSlug}>
              <div className="card hover:scale-105 duration-300 hover:ease-in-out">
                <div className='card_top'>
                <h3 className='card_title'>{val.attributes.title}</h3>
                <p className='time'>{val.attributes.date}</p>
                </div>
                <p className='card_desc'>{val.attributes.description}</p>
                <p className='user'>{val.attributes.author}</p>
              </div>
          </Link>
        )
      })}
</div>
    </div>
  )
}

export async function getStaticProps() {

  const client = new ApolloClient({
    uri: "http://127.0.0.1:1337/graphql",
    cache: new InMemoryCache()
  });

  const { data } = await client.query({
    query: GET_ALL_POSTS
  })

  return {
    props: {
      posts: data.blogPosts.data
    }
  }
}
